name: my_rag
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    # optionally use a convenient Ubuntu LTS + DVC + CML image
    # container: ghcr.io/iterative/cml:0-dvc2-base1
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      # may need to setup NodeJS & Python3 on e.g. self-hosted
      # - uses: actions/setup-node@v3
      #   with:
      #     node-version: '16'
      # - uses: actions/setup-python@v4
      #   with:
      #     python-version: '3.x'
      - name: Run Super-Linter
        uses: github/super-linter@v3
        env: 
         DEFAULT_BRANCH: main
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
      - uses: iterative/setup-cml@v1
      # - name: Train model
      #   run: |
      #     # Your ML workflow goes here
      #     pip install -r requirements.txt
      #     python train.py
