name: my_rag

on:
  push:
    branches:
      - main  # Optionally specify the branch or branches to trigger on

jobs:
  run:
    runs-on: ubuntu-latest
    
    # Optionally use a convenient Ubuntu LTS + DVC + CML image
    # container: ghcr.io/iterative/cml:0-dvc2-base1

    steps:
      # Step 1: Checkout code from the repository
      - name: Checkout code
        uses: actions/checkout@v3
        
      - uses: actions/setup-node@v3
        with:
          node-version: '16'

      # Step 2: Setup Python environment
      - name: Setup Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.0'

          
      - name: Install isort
        run: pip install isort
  
      - name: Auto-format imports with isort
        run: isort run.py
        
      # Step 3: Run Super-Linter to check for code quality issues
      - name: Run Super-Linter
        uses: github/super-linter@latest
        env: 
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Step 4: Setup CML (Continuous Machine Learning) for ML workflow tracking
      - name: Setup CML
        uses: iterative/setup-cml@v1

      # Step 5: Train the model
      - name: Train model
        run: |
          # Install dependencies from requirements.txt
          pip install -r requirements.txt
          
          # Run the training script
          python run.py
